# Generated by Django 5.0.3 on 2024-04-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SodaCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('soda', models.CharField(max_length=100)),
                ('flavor1', models.CharField(max_length=100)),
                ('flavor2', models.CharField(blank=True, max_length=100, null=True)),
                ('flavor3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
