# Generated by Django 5.0.3 on 2024-04-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sodas', '0002_sodacombo_addon1_sodacombo_addon2_sodacombo_flavor4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sodacombo',
            name='flavor1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
